BEGIN TRANSACTION;
CREATE TABLE PUZZLE_DATA
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PUZZLE_NAME CHAR(16) NOT NULL,
	CREATOR CHAR(16) NOT NULL,
	PUZZLE_FILE BLOB,
	DOWNLOADED INTEGER NOT NULL
);
CREATE TABLE PLAYER_DATA
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DC_ID CHAR(8) NOT NULL,
	USERNAME CHAR(16) NOT NULL,
	PASSWORD CHAR(16) NOT NULL,
	WON_RNDS INTEGER,
	LOST_RNDS INTEGER,
	TOTAL_RNDS INTEGER
);
COMMIT;


